-- ============================================================
-- LDR-Connect: Schema Fresh — 06 Seed Pertanyaan Ular Tangga
-- Jalankan SETELAH 05_seed_tod_questions.sql
--
-- 100 pertanyaan Truth or Dare untuk game Ular Tangga
-- Kategori: romantis, kenangan, harapan, umum, tantangan, seru
-- ============================================================

INSERT INTO public.game_snake_questions (type, category, question) VALUES
-- ── TRUTH: Romantis ──────────────────────────────────────────
('truth','romantis','Apa hal pertama yang kamu perhatikan dari aku ketika pertama kali bertemu?'),
('truth','romantis','Kapan kamu sadar kalau kamu menyukaiku?'),
('truth','romantis','Apa yang paling kamu rindukan dari aku saat ini?'),
('truth','romantis','Pernahkah kamu menangis karena memikirkan jarak antara kita?'),
('truth','romantis','Apa lagu yang selalu mengingatkanmu padaku?'),
('truth','romantis','Apa hal kecil tentang aku yang paling membuatmu jatuh cinta?'),
('truth','romantis','Seberapa sering kamu memikirkan aku dalam sehari?'),
('truth','romantis','Apa mimpi paling indah yang pernah melibatkan aku?'),
('truth','romantis','Bagaimana kamu mendeskripsikan perasaanmu untukku kepada orang lain?'),
('truth','romantis','Apa kata-kata yang paling ingin kamu dengar dariku?'),
-- ── TRUTH: Kenangan ──────────────────────────────────────────
('truth','kenangan','Apa momen paling lucu yang pernah kita alami bersama?'),
('truth','kenangan','Apa kenangan pertama yang kamu ingat tentang kita?'),
('truth','kenangan','Momen apa yang paling berkesan dalam hubungan kita hingga saat ini?'),
('truth','kenangan','Apa hal paling konyol yang pernah kita lakukan bersama?'),
('truth','kenangan','Apa momen yang membuat kamu paling bangga dengan hubungan kita?'),
('truth','kenangan','Kapan momen paling romantis kita menurutmu?'),
('truth','kenangan','Kenangan apa yang selalu membuatmu tersenyum saat mengingatnya?'),
('truth','kenangan','Apa pertengkaran kita yang sudah kamu maafkan dan kenapa?'),
('truth','kenangan','Momen apa yang membuat kamu merasa paling dekat denganku?'),
('truth','kenangan','Apa momen pertama kali kita jujur satu sama lain yang paling kamu ingat?'),
-- ── TRUTH: Harapan ───────────────────────────────────────────
('truth','harapan','Di mana kamu membayangkan kita tinggal bersama suatu hari nanti?'),
('truth','harapan','Apa yang paling kamu tunggu-tunggu untuk kita lakukan saat sudah bersama?'),
('truth','harapan','Dalam 5 tahun ke depan, bagaimana kamu membayangkan kehidupan kita?'),
('truth','harapan','Seperti apa rumah impian kita menurutmu?'),
('truth','harapan','Apa tradisi yang ingin kamu buat bersama dalam hubungan kita?'),
('truth','harapan','Di mana tempat yang paling ingin kamu kunjungi bersamaku?'),
('truth','harapan','Apa hal pertama yang ingin kamu lakukan saat kita bertemu nanti?'),
('truth','harapan','Seperti apa liburan impianmu bersamaku?'),
('truth','harapan','Apa yang ingin kamu capai bersama dalam hubungan ini?'),
('truth','harapan','Apa resolusimu untuk hubungan kita ke depannya?'),
-- ── TRUTH: Umum ──────────────────────────────────────────────
('truth','umum','Apa kebiasaan burukmu yang kamu rasa aku belum tahu?'),
('truth','umum','Siapa orang pertama yang kamu ceritakan tentang aku?'),
('truth','umum','Apa yang membuatmu tetap setia dalam hubungan jarak jauh ini?'),
('truth','umum','Apa hal yang paling kamu takutkan dari hubungan kita?'),
('truth','umum','Apa hal yang ingin kamu ubah dari dirimu untuk hubungan kita?'),
('truth','umum','Apa yang kamu lakukan saat kangen aku tapi tidak bisa menghubungiku?'),
('truth','umum','Apa hal yang kamu ingin aku tahu tapi belum pernah kamu bilang?'),
('truth','umum','Apa yang membuat kamu yakin bahwa aku adalah orang yang tepat untukmu?'),
('truth','umum','Bagaimana cara kamu mengatasi rindu saat kita tidak bisa video call?'),
('truth','umum','Apa hal yang paling kamu syukuri dari hubungan kita?'),
('truth','umum','Apa kualitasmu yang kamu rasa paling aku sukai?'),
('truth','umum','Pernahkah kamu ragu dengan hubungan kita? Apa yang membuatmu bertahan?'),
('truth','umum','Apa hal yang paling susah dari menjalani LDR menurutmu?'),
('truth','umum','Apa yang ingin kamu katakan padaku yang belum pernah kamu ucapkan?'),
('truth','umum','Apa hal yang selalu membuatmu tersenyum meskipun sedang sedih?'),
('truth','umum','Siapa yang pertama kali bilang suka atau cinta di antara kita?'),
('truth','umum','Apa keputusan terberat yang pernah kamu buat untuk hubungan kita?'),
('truth','umum','Apa hal yang paling kamu hargai dari aku sebagai pasanganmu?'),
('truth','umum','Apa hal yang ingin kamu ketahui lebih dalam tentang aku?'),
('truth','umum','Jika bisa mengulang waktu, apa yang ingin kamu lakukan berbeda dalam hubungan kita?'),
-- ── DARE: Tantangan ──────────────────────────────────────────
('dare','tantangan','Kirimkan foto selfie paling aneh yang bisa kamu buat sekarang!'),
('dare','tantangan','Nyanyikan bait pertama lagu favorit kita dan kirimkan audionya!'),
('dare','tantangan','Tulis puisi 4 baris tentang aku sekarang dan bacakan!'),
('dare','tantangan','Lakukan 10 jumping jacks sambil meneriakkan namaku!'),
('dare','tantangan','Gambar wajahku tanpa mengangkat pensil dari kertas dan kirimkan hasilnya!'),
('dare','tantangan','Ceritakan lelucon terbaik yang kamu tahu sekarang!'),
('dare','tantangan','Rekam video 15 detik menari dengan lagu favoritmu sekarang!'),
('dare','tantangan','Kirimkan screenshot wallpaper HP-mu saat ini!'),
('dare','tantangan','Lakukan ekspresi wajah paling lebay yang bisa kamu buat dan foto!'),
('dare','tantangan','Buat sandwich atau makanan kreatif dari bahan yang ada dan foto hasilnya!'),
('dare','tantangan','Ceritakan mimpi paling aneh yang pernah kamu alami secara detail!'),
('dare','tantangan','Lakukan gerakan yoga atau stretching selama 1 menit penuh!'),
('dare','tantangan','Rekam video saat kamu tertawa sekeras mungkin selama 10 detik!'),
('dare','tantangan','Kirimkan foto pemandangan dari jendela kamarmu sekarang!'),
('dare','tantangan','Tulis namaku sebanyak 20 kali di kertas dan foto hasilnya!'),
('dare','tantangan','Buat suara 5 hewan berbeda dalam 30 detik tanpa berhenti!'),
('dare','tantangan','Kirimkan foto meja belajar atau kerjamu sekarang apa adanya!'),
('dare','tantangan','Berpose layaknya model majalah fashion dan kirimkan fotonya!'),
('dare','tantangan','Lakukan 15 sit-up dan kirimkan video buktinya!'),
('dare','tantangan','Rekam suaramu saat membaca teks berita dengan aksen daerah yang berbeda!'),
-- ── DARE: Romantis ───────────────────────────────────────────
('dare','romantis','Rekam video mengucapkan 5 hal yang kamu suka dari aku!'),
('dare','romantis','Kirimkan pesan suara berisi lagu yang kamu buat sendiri tentang kita!'),
('dare','romantis','Tulis surat cinta singkat dan bacakan atau foto hasilnya!'),
('dare','romantis','Screenshot percakapan favoritmu dengan aku dan kirimkan!'),
('dare','romantis','Rekam video saat kamu mengucapkan aku sayang kamu dalam 5 bahasa berbeda!'),
('dare','romantis','Gambar kita berdua versi stick figure dan kirimkan!'),
('dare','romantis','Kirimkan foto objek yang mengingatkanmu padaku beserta penjelasannya!'),
('dare','romantis','Buat playlist lagu yang mewakili perasaanmu untukku dan bagikan!'),
('dare','romantis','Ceritakan kenangan favoritmu bersamaku dengan detail sebanyak mungkin!'),
('dare','romantis','Rekam video memberikan virtual hug dan ciuman untuk aku!'),
('dare','romantis','Kirimkan voice note berisi hal-hal yang kamu syukuri tentang hubungan kita!'),
('dare','romantis','Foto dirimu dengan memegang kertas bertuliskan namaku!'),
-- ── DARE: Seru ───────────────────────────────────────────────
('dare','seru','Cari tahu satu fakta unik tentang kota tempatku tinggal sekarang!'),
('dare','seru','Kirimkan foto dirimu dari 1-2 tahun yang lalu!'),
('dare','seru','Screenshot galeri foto HP-mu bagian terbaru dan kirimkan!'),
('dare','seru','Rekam video sambil menjelaskan profilku seperti seorang presenter berita!'),
('dare','seru','Tuliskan 10 kata yang menggambarkan aku dalam waktu 60 detik!'),
('dare','seru','Cari dan kirimkan meme yang paling menggambarkan hubungan kita!'),
('dare','seru','Lakukan selfie di ruangan yang berbeda dari tempat biasamu!'),
('dare','seru','Kirimkan foto sepatumu yang paling sering kamu pakai!'),
('dare','seru','Buat gerakan dance sendiri selama 15 detik dan rekam!'),
('dare','seru','Ceritakan hal paling memalukan yang pernah kamu lakukan di depan orang banyak!'),
('dare','seru','Rekam video saat kamu mencoba menggigit sikumu sendiri!'),
('dare','seru','Kirimkan foto selfie dengan ekspresi sesuai mood-mu saat ini!'),
('dare','seru','Tebak berapa pesan yang sudah kita kirimkan hari ini dan cek hasilnya!'),
('dare','seru','Kirimkan foto benda paling aneh yang ada di kamarmu sekarang!'),
('dare','seru','Rekam video tutorial singkat cara melakukan hal yang kamu kuasai!'),
('dare','seru','Kirimkan voice note berisi 3 hal lucu yang terjadi padamu hari ini!'),
('dare','seru','Foto dirimu dengan pose paling dramatis yang bisa kamu buat!'),
('dare','seru','Buat dan kirimkan caption Instagram untuk foto profilmu saat ini!');
